# FERRETCANNON Matrix Server Configuration - Production
# This file contains production-ready settings for fly.io deployment

server:
  # Server network settings
  host: "0.0.0.0"  # IP address to bind to (0.0.0.0 for all interfaces)
  port: 8080       # Port to listen on (matches fly.io internal_port)
  maxRequestSize: 1048576  # Maximum request size in bytes (1MB)
  corsAllowedOrigins:       # List of allowed CORS origins
    - "*"                   # Configure specific domains as needed

database:
  # Database connection settings
  url: "jdbc:sqlite:/data/ferretcannon.db"  # Database in persistent volume
  driver: "org.sqlite.JDBC"           # JDBC driver class
  maxConnections: 5                   # Reduced for fly.io shared CPU
  connectionTimeout: 30000            # Connection timeout in milliseconds

federation:
  # Federation settings for server-to-server communication
  serverName: "your-server-name.fly.dev"  # Replace with your actual fly.io domain
  federationPort: 443                # Port for federation endpoints
  enableFederation: true              # Enable/disable federation
  allowedServers:                     # List of allowed federation servers
    - "*"                             # Configure specific servers as needed
  keyValidityPeriod: 86400000         # Server key validity period in milliseconds

security:
  # Security and authentication settings
  jwtSecret: "your-secure-jwt-secret-here-change-this-in-production"  # CHANGE THIS!
  tokenExpirationHours: 24            # Access token expiration time
  bcryptRounds: 12                    # BCrypt password hashing rounds
  rateLimitRequests: 100              # Reduced rate limit for shared resources
  rateLimitPeriodMinutes: 1           # Rate limit: period in minutes
  enableRateLimiting: true            # Enable rate limiting in production

media:
  # Media upload and storage settings
  maxUploadSize: 5242880              # Reduced to 5MB for fly.io
  maxImageSize: 5242880               # Reduced to 5MB for fly.io
  maxAvatarSize: 1048576              # Maximum avatar size in bytes (1MB)
  maxThumbnailSize: 1048576           # Maximum thumbnail size in bytes (1MB)
  thumbnailSizes:                     # Available thumbnail sizes
    - width: 32
      height: 32
      method: "crop"
    - width: 96
      height: 96
      method: "crop"
    - width: 320
      height: 240
      method: "scale"
    - width: 640
      height: 480
      method: "scale"

development:
  # Development and testing settings - DISABLED IN PRODUCTION
  createTestUser: false               # DO NOT create test user in production
  testUsername: ""                    # Not used in production
  testPassword: ""                    # Not used in production
  testDisplayName: ""                 # Not used in production
  enableDebugLogging: false           # Disable debug logging in production
  enableWebSocketDebug: false         # Disable WebSocket debug logging
